name: publish on pypi.org

on:
  workflow_dispatch:
  push:
    tags:
      - v**

jobs:
  build-n-publish:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: determine version
        uses: mtkennerly/dunamai-action@v1
        with:
          env-var: VERSION
          args: --style semver
      - run: echo using tagged version $VERSION
      - name: Build
        run: python -m build --sdist --wheel --outdir dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
