name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: run tests
        run: cd tests && ./run.sh || exit 1
